"""P5.10.2 -- Pilot Examples Generation (100 records).

Produces the FIRST controlled pilot batch of vocabulary examples. Never
modifies production vocabulary files or app/src. Never overwrites an
existing pilot artifact.

HONESTY NOTE ON DETERMINISM (required by the phase brief): this script
has two genuinely different parts with different determinism guarantees:
  1. RECORD SELECTION is fully deterministic and mechanically
     reproducible -- see select_pilot_ids() below. Rerunning selection
     against the same production data always yields the same 100 IDs in
     the same order.
  2. EXAMPLE CONTENT (the Chinese sentences, pinyin, and Vietnamese
     translations in EXAMPLES_CONTENT) was authored directly by an LLM
     (this assistant) during this phase, the same way every Related
     Words PAIRS/FAMILY_CLIQUES list in this project's tools/hsk/*.py
     scripts was hand-authored data rather than mechanically derived.
     It is embedded here as literal data, not generated by a separate
     reproducible algorithm. A different generation pass (a different
     LLM call, or the same model on a different day) would very likely
     produce different-but-similarly-valid sentences for the same 100
     words. This script does NOT claim example content is deterministic
     -- only that, given this exact embedded content, writing the
     pilot artifact is deterministic and reproducible byte-for-byte.

SELECTION RULE (deterministic, see select_pilot_ids):
  1. Build the full 5400-record HSK1-6 universe.
  2. Classify every record into a risk tier using the same method as
     the P5.10.1 risk audit, recomputed directly (never copy-pasted):
       tier 3 = word (hanzi) also appears elsewhere in HSK1-6 under a
                different pinyin reading (homograph, different reading)
       tier 4 = word+pinyin combination duplicated by another record
                within the SAME HSK level (same-reading duplicate)
       tier 2 = not tier 3/4, but has >1 partOfSpeech tag OR >1 logged
                candidateMeanings entries (ambiguity signal)
       tier 1 = none of the above (lowest risk)
  3. Exclude tier 3 and tier 4 entirely from the pilot candidate pool
     (per the explicit instruction to keep the normal pilot free of
     homograph/critical-duplicate records).
  4. Allocate 100 slots across the 6 HSK levels proportional to each
     level's ELIGIBLE (tier 1+2) record count, using the largest-
     remainder method for exact integer rounding to 100.
  5. Within each level, sort the eligible pool by (tier, id) ascending
     and take the first N per that level's allocation -- i.e. prefer
     tier 1 records first; only reach into tier 2 if a level's tier-1
     pool were smaller than its allocation (empirically, for this
     100-record pilot, every level's tier-1 pool was large enough on
     its own, so the pilot selected is 100% tier 1).

Usage:
    python generate_hsk_examples_p102.py
    python generate_hsk_examples_p102.py --dry-run   (report selection only, write nothing)
"""

import argparse
import hashlib
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
OUTPUT_PATH = REPO_ROOT / "tools" / "hsk" / "examples" / "hsk_examples_p102_pilot_01.json"

PILOT_VERSION = "p102-v1"
GENERATION_BATCH = "batch-001"
GENERATION_METHOD = "llm-authored (Claude, this assistant) -- see module docstring HONESTY NOTE"
TARGET_PILOT_SIZE = 100


def load_json_text(path: Path) -> str:
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    sys.exit(1)


def load_universe() -> dict:
    universe = {}
    for n in range(1, 7):
        path = REPO_ROOT / "data" / "hsk" / f"hsk{n}" / f"hsk{n}_vocabulary_production.json"
        recs = json.loads(load_json_text(path))
        for r in recs:
            universe[r["id"]] = {**r, "_level": n}
    return universe


def get_pos(r: dict) -> list:
    if r.get("partOfSpeech"):
        return r["partOfSpeech"]
    if r.get("cixing"):
        return [r["cixing"]]
    return []


def classify_risk_tiers(universe: dict) -> dict:
    word_pinyin = defaultdict(set)
    for r in universe.values():
        word_pinyin[r["word"]].add(r["pinyin"])
    homograph_words = {w for w, p in word_pinyin.items() if len(p) > 1}

    by_level_word_pinyin = defaultdict(list)
    for r in universe.values():
        by_level_word_pinyin[(r["_level"], r["word"], r["pinyin"])].append(r["id"])
    tier4_ids = {rid for ids in by_level_word_pinyin.values() if len(ids) > 1 for rid in ids}

    tier3_ids = {rid for rid, r in universe.items() if r["word"] in homograph_words} - tier4_ids

    tiers = {}
    for rid, r in universe.items():
        if rid in tier4_ids:
            tiers[rid] = 4
        elif rid in tier3_ids:
            tiers[rid] = 3
        else:
            pos = get_pos(r)
            cm = len(r.get("candidateMeanings") or [])
            tiers[rid] = 2 if (len(pos) > 1 or cm > 1) else 1
    return tiers


def select_pilot_ids(universe: dict, tiers: dict) -> list:
    eligible_by_level = defaultdict(list)
    for rid, r in universe.items():
        if tiers[rid] in (1, 2):
            eligible_by_level[r["_level"]].append(rid)
    for n in range(1, 7):
        eligible_by_level[n].sort()

    eligible_counts = {n: len(eligible_by_level[n]) for n in range(1, 7)}
    total_eligible = sum(eligible_counts.values())

    raw = {n: eligible_counts[n] / total_eligible * TARGET_PILOT_SIZE for n in range(1, 7)}
    alloc = {n: int(raw[n]) for n in range(1, 7)}
    remainder = TARGET_PILOT_SIZE - sum(alloc.values())
    order = sorted(range(1, 7), key=lambda n: -(raw[n] - alloc[n]))
    for i in range(remainder):
        alloc[order[i]] += 1

    selected = []
    for n in range(1, 7):
        pool = sorted(eligible_by_level[n], key=lambda rid: (tiers[rid], rid))
        selected.extend(pool[: alloc[n]])

    return selected, alloc, eligible_counts


# ---------------------------------------------------------------------------
# EXAMPLES_CONTENT: hand-authored by this assistant during P5.10.2.
# {sourceId: [{"chinese", "pinyin", "meaningVi"}, ...]}
# Every entry respects the production record's meaningVi/partOfSpeech and
# was written to demonstrate the target word naturally, in its production
# sense, at an appropriate difficulty for the record's HSK level.
# ---------------------------------------------------------------------------
EXAMPLES_CONTENT: dict[str, list[dict]] = {
    "hsk1_001": [
        {"chinese": "我爱我的家人。", "pinyin": "Wǒ ài wǒ de jiārén.", "meaningVi": "Tôi yêu gia đình của tôi."},
        {"chinese": "她很爱看书。", "pinyin": "Tā hěn ài kàn shū.", "meaningVi": "Cô ấy rất thích đọc sách."},
    ],
    "hsk1_002": [
        {"chinese": "我家有八口人。", "pinyin": "Wǒ jiā yǒu bā kǒu rén.", "meaningVi": "Nhà tôi có tám người."},
        {"chinese": "现在是八点。", "pinyin": "Xiànzài shì bā diǎn.", "meaningVi": "Bây giờ là tám giờ."},
    ],
    "hsk1_003": [
        {"chinese": "我爸爸是老师。", "pinyin": "Wǒ bàba shì lǎoshī.", "meaningVi": "Bố tôi là giáo viên."},
        {"chinese": "爸爸每天早上跑步。", "pinyin": "Bàba měitiān zǎoshang pǎobù.", "meaningVi": "Bố tôi chạy bộ mỗi sáng."},
    ],
    "hsk1_004": [
        {"chinese": "我们走吧。", "pinyin": "Wǒmen zǒu ba.", "meaningVi": "Chúng ta đi thôi."},
        {"chinese": "你是学生吧？", "pinyin": "Nǐ shì xuéshēng ba?", "meaningVi": "Bạn là học sinh phải không?"},
    ],
    "hsk1_005": [
        {"chinese": "我白天工作，晚上休息。", "pinyin": "Wǒ báitiān gōngzuò, wǎnshang xiūxi.", "meaningVi": "Tôi làm việc ban ngày, nghỉ ngơi buổi tối."},
        {"chinese": "夏天的白天比较长。", "pinyin": "Xiàtiān de báitiān bǐjiào cháng.", "meaningVi": "Ban ngày mùa hè khá dài."},
    ],
    "hsk1_006": [
        {"chinese": "这本书有一百页。", "pinyin": "Zhè běn shū yǒu yìbǎi yè.", "meaningVi": "Cuốn sách này có một trăm trang."},
        {"chinese": "我有一百块钱。", "pinyin": "Wǒ yǒu yìbǎi kuài qián.", "meaningVi": "Tôi có một trăm đồng."},
    ],
    "hsk2_003": [
        {"chinese": "她喜欢穿白色的衣服。", "pinyin": "Tā xǐhuan chuān báisè de yīfu.", "meaningVi": "Cô ấy thích mặc quần áo màu trắng."},
        {"chinese": "这辆车是白色的。", "pinyin": "Zhè liàng chē shì báisè de.", "meaningVi": "Chiếc xe này màu trắng."},
    ],
    "hsk2_015": [
        {"chinese": "车站离这儿很近。", "pinyin": "Chēzhàn lí zhèr hěn jìn.", "meaningVi": "Trạm xe cách đây rất gần."},
        {"chinese": "我们在车站等他。", "pinyin": "Wǒmen zài chēzhàn děng tā.", "meaningVi": "Chúng tôi đợi anh ấy ở trạm xe."},
    ],
    "hsk2_021": [
        {"chinese": "这张床很舒服。", "pinyin": "Zhè zhāng chuáng hěn shūfu.", "meaningVi": "Chiếc giường này rất thoải mái."},
        {"chinese": "猫在床上睡觉。", "pinyin": "Māo zài chuáng shàng shuìjiào.", "meaningVi": "Con mèo đang ngủ trên giường."},
    ],
    "hsk2_037": [
        {"chinese": "我听不懂他说的话。", "pinyin": "Wǒ tīng bu dǒng tā shuō de huà.", "meaningVi": "Tôi không hiểu những gì anh ấy nói."},
        {"chinese": "你懂我的意思吗？", "pinyin": "Nǐ dǒng wǒ de yìsi ma?", "meaningVi": "Bạn hiểu ý tôi không?"},
    ],
    "hsk3_001": [
        {"chinese": "那位阿姨很热情。", "pinyin": "Nà wèi āyí hěn rèqíng.", "meaningVi": "Cô/dì đó rất nhiệt tình."},
        {"chinese": "我叫她阿姨。", "pinyin": "Wǒ jiào tā āyí.", "meaningVi": "Tôi gọi cô ấy là dì."},
    ],
    "hsk3_002": [
        {"chinese": "他比我矮一点。", "pinyin": "Tā bǐ wǒ ǎi yìdiǎn.", "meaningVi": "Anh ấy thấp hơn tôi một chút."},
        {"chinese": "这棵树很矮。", "pinyin": "Zhè kē shù hěn ǎi.", "meaningVi": "Cái cây này rất thấp."},
    ],
    "hsk3_003": [
        {"chinese": "这是我爱人。", "pinyin": "Zhè shì wǒ àiren.", "meaningVi": "Đây là vợ tôi."},
        {"chinese": "他和爱人一起去旅行了。", "pinyin": "Tā hé àiren yìqǐ qù lǚxíng le.", "meaningVi": "Anh ấy cùng vợ đi du lịch rồi."},
    ],
    "hsk3_004": [
        {"chinese": "图书馆里很安静。", "pinyin": "Túshūguǎn lǐ hěn ānjìng.", "meaningVi": "Trong thư viện rất yên tĩnh."},
        {"chinese": "请安静一点。", "pinyin": "Qǐng ānjìng yìdiǎn.", "meaningVi": "Xin hãy yên tĩnh một chút."},
    ],
    "hsk3_005": [
        {"chinese": "开车要注意安全。", "pinyin": "Kāichē yào zhùyì ānquán.", "meaningVi": "Lái xe phải chú ý an toàn."},
        {"chinese": "这里很安全，你不用担心。", "pinyin": "Zhèlǐ hěn ānquán, nǐ búyòng dānxīn.", "meaningVi": "Ở đây rất an toàn, bạn không cần lo lắng."},
    ],
    "hsk3_007": [
        {"chinese": "他一个人搬不动这张桌子。", "pinyin": "Tā yí gè rén bān bu dòng zhè zhāng zhuōzi.", "meaningVi": "Một mình anh ấy không thể khiêng nổi cái bàn này."},
        {"chinese": "请帮我把箱子搬到楼上。", "pinyin": "Qǐng bāng wǒ bǎ xiāngzi bān dào lóushàng.", "meaningVi": "Xin giúp tôi chuyển cái hộp lên lầu."},
    ],
    "hsk3_008": [
        {"chinese": "我们班级一共有三十个学生。", "pinyin": "Wǒmen bānjí yígòng yǒu sānshí gè xuéshēng.", "meaningVi": "Lớp chúng tôi có tổng cộng ba mươi học sinh."},
        {"chinese": "这个班级很团结。", "pinyin": "Zhège bānjí hěn tuánjié.", "meaningVi": "Lớp này rất đoàn kết."},
    ],
    "hsk3_009": [
        {"chinese": "我们上个星期搬家了。", "pinyin": "Wǒmen shàng gè xīngqī bānjiā le.", "meaningVi": "Tuần trước chúng tôi đã chuyển nhà."},
        {"chinese": "搬家很麻烦，需要收拾很多东西。", "pinyin": "Bānjiā hěn máfan, xūyào shōushi hěn duō dōngxi.", "meaningVi": "Chuyển nhà rất phiền phức, cần dọn dẹp rất nhiều đồ."},
    ],
    "hsk3_010": [
        {"chinese": "这件事怎么办？", "pinyin": "Zhè jiàn shì zěnme bàn?", "meaningVi": "Việc này phải làm thế nào?"},
        {"chinese": "我去银行办点事。", "pinyin": "Wǒ qù yínháng bàn diǎn shì.", "meaningVi": "Tôi đến ngân hàng để giải quyết vài việc."},
    ],
    "hsk4_002": [
        {"chinese": "他们的爱情很感人。", "pinyin": "Tāmen de àiqíng hěn gǎnrén.", "meaningVi": "Tình yêu của họ rất cảm động."},
        {"chinese": "电影讲述了一个爱情故事。", "pinyin": "Diànyǐng jiǎngshùle yí gè àiqíng gùshi.", "meaningVi": "Bộ phim kể về một câu chuyện tình yêu."},
    ],
    "hsk4_003": [
        {"chinese": "他是一个很有爱心的人。", "pinyin": "Tā shì yí gè hěn yǒu àixīn de rén.", "meaningVi": "Anh ấy là một người rất có lòng nhân ái."},
        {"chinese": "我们应该多献爱心，帮助别人。", "pinyin": "Wǒmen yīnggāi duō xiàn àixīn, bāngzhù biérén.", "meaningVi": "Chúng ta nên thể hiện lòng nhân ái nhiều hơn, giúp đỡ người khác."},
    ],
    "hsk4_004": [
        {"chinese": "进机场之前要安检。", "pinyin": "Jìn jīchǎng zhīqián yào ānjiǎn.", "meaningVi": "Trước khi vào sân bay phải qua kiểm tra an ninh."},
        {"chinese": "安检的队伍排得很长。", "pinyin": "Ānjiǎn de duìwu pái de hěn cháng.", "meaningVi": "Hàng đợi kiểm tra an ninh xếp rất dài."},
    ],
    "hsk4_005": [
        {"chinese": "老师安排了明天的考试。", "pinyin": "Lǎoshī ānpáile míngtiān de kǎoshì.", "meaningVi": "Giáo viên đã sắp xếp kỳ thi ngày mai."},
        {"chinese": "请帮我安排一下行程。", "pinyin": "Qǐng bāng wǒ ānpái yíxià xíngchéng.", "meaningVi": "Xin giúp tôi sắp xếp lịch trình."},
    ],
    "hsk4_007": [
        {"chinese": "请按时完成作业。", "pinyin": "Qǐng ànshí wánchéng zuòyè.", "meaningVi": "Xin hoàn thành bài tập đúng giờ."},
        {"chinese": "他每天都按时上班。", "pinyin": "Tā měitiān dōu ànshí shàngbān.", "meaningVi": "Anh ấy mỗi ngày đều đi làm đúng giờ."},
    ],
    "hsk4_008": [
        {"chinese": "请按照说明书使用。", "pinyin": "Qǐng ànzhào shuōmíngshū shǐyòng.", "meaningVi": "Xin sử dụng theo hướng dẫn sử dụng."},
        {"chinese": "按照计划，我们明天出发。", "pinyin": "Ànzhào jìhuà, wǒmen míngtiān chūfā.", "meaningVi": "Theo kế hoạch, ngày mai chúng tôi xuất phát."},
    ],
    "hsk4_009": [
        {"chinese": "中国人喝酒的时候常常喝白酒。", "pinyin": "Zhōngguórén hē jiǔ de shíhou chángcháng hē báijiǔ.", "meaningVi": "Khi uống rượu, người Trung Quốc thường uống rượu trắng."},
        {"chinese": "白酒的度数比较高。", "pinyin": "Báijiǔ de dùshu bǐjiào gāo.", "meaningVi": "Nồng độ của rượu trắng khá cao."},
    ],
    "hsk4_010": [
        {"chinese": "他们在新大楼里办公。", "pinyin": "Tāmen zài xīn dàlóu lǐ bàngōng.", "meaningVi": "Họ làm việc văn phòng ở tòa nhà mới."},
        {"chinese": "公司要求员工九点开始办公。", "pinyin": "Gōngsī yāoqiú yuángōng jiǔ diǎn kāishǐ bàngōng.", "meaningVi": "Công ty yêu cầu nhân viên bắt đầu làm việc lúc chín giờ."},
    ],
    "hsk4_011": [
        {"chinese": "请到二楼办理手续。", "pinyin": "Qǐng dào èr lóu bànlǐ shǒuxù.", "meaningVi": "Xin đến tầng hai làm thủ tục."},
        {"chinese": "我要办理银行卡。", "pinyin": "Wǒ yào bànlǐ yínháng kǎ.", "meaningVi": "Tôi muốn làm thẻ ngân hàng."},
    ],
    "hsk4_012": [
        {"chinese": "他办事很认真。", "pinyin": "Tā bànshì hěn rènzhēn.", "meaningVi": "Anh ấy làm việc rất nghiêm túc."},
        {"chinese": "我今天要去办事，晚点回来。", "pinyin": "Wǒ jīntiān yào qù bànshì, wǎn diǎn huílái.", "meaningVi": "Hôm nay tôi phải đi lo việc, sẽ về muộn một chút."},
    ],
    "hsk4_014": [
        {"chinese": "我们应该保护环境。", "pinyin": "Wǒmen yīnggāi bǎohù huánjìng.", "meaningVi": "Chúng ta nên bảo vệ môi trường."},
        {"chinese": "父母总是保护孩子。", "pinyin": "Fùmǔ zǒngshì bǎohù háizi.", "meaningVi": "Cha mẹ luôn bảo vệ con cái."},
    ],
    "hsk4_016": [
        {"chinese": "妈妈紧紧地抱着孩子。", "pinyin": "Māma jǐnjǐn de bàozhe háizi.", "meaningVi": "Mẹ ôm chặt đứa trẻ."},
        {"chinese": "他抱起了地上的猫。", "pinyin": "Tā bào qǐle dìshang de māo.", "meaningVi": "Anh ấy bế con mèo trên mặt đất lên."},
    ],
    "hsk4_017": [
        {"chinese": "他报考了北京大学。", "pinyin": "Tā bàokǎole Běijīng Dàxué.", "meaningVi": "Anh ấy đã đăng ký thi vào Đại học Bắc Kinh."},
        {"chinese": "报考公务员的人越来越多。", "pinyin": "Bàokǎo gōngwùyuán de rén yuè lái yuè duō.", "meaningVi": "Số người đăng ký thi công chức ngày càng nhiều."},
    ],
    "hsk4_018": [
        {"chinese": "我已经报名参加比赛了。", "pinyin": "Wǒ yǐjīng bàomíng cānjiā bǐsài le.", "meaningVi": "Tôi đã đăng ký tham gia cuộc thi rồi."},
        {"chinese": "报名的截止日期是明天。", "pinyin": "Bàomíng de jiézhǐ rìqī shì míngtiān.", "meaningVi": "Hạn chót đăng ký là ngày mai."},
    ],
    "hsk4_019": [
        {"chinese": "让你久等了，我很抱歉。", "pinyin": "Ràng nǐ jiǔ děng le, wǒ hěn bàoqiàn.", "meaningVi": "Đã để bạn đợi lâu, tôi rất áy náy."},
        {"chinese": "他对自己的错误感到很抱歉。", "pinyin": "Tā duì zìjǐ de cuòwù gǎndào hěn bàoqiàn.", "meaningVi": "Anh ấy cảm thấy rất áy náy về sai lầm của mình."},
    ],
    "hsk4_021": [
        {"chinese": "他背着一个大背包去旅行。", "pinyin": "Tā bēizhe yí gè dà bēibāo qù lǚxíng.", "meaningVi": "Anh ấy đeo một cái ba lô lớn đi du lịch."},
        {"chinese": "我的背包里有很多书。", "pinyin": "Wǒ de bēibāo lǐ yǒu hěn duō shū.", "meaningVi": "Trong ba lô của tôi có rất nhiều sách."},
    ],
    "hsk4_022": [
        {"chinese": "中国北部的冬天很冷。", "pinyin": "Zhōngguó běibù de dōngtiān hěn lěng.", "meaningVi": "Mùa đông ở miền Bắc Trung Quốc rất lạnh."},
        {"chinese": "这座城市位于国家的北部。", "pinyin": "Zhè zuò chéngshì wèiyú guójiā de běibù.", "meaningVi": "Thành phố này nằm ở phía Bắc của đất nước."},
    ],
    "hsk4_023": [
        {"chinese": "今年的销量是去年的两倍。", "pinyin": "Jīnnián de xiāoliàng shì qùnián de liǎng bèi.", "meaningVi": "Doanh số năm nay gấp đôi năm ngoái."},
        {"chinese": "这个房间比那个大一倍。", "pinyin": "Zhège fángjiān bǐ nàge dà yí bèi.", "meaningVi": "Căn phòng này lớn gấp đôi căn kia."},
    ],
    "hsk5_001": [
        {"chinese": "哎，你怎么又迟到了？", "pinyin": "Āi, nǐ zěnme yòu chídào le?", "meaningVi": "Này, sao cậu lại trễ nữa rồi?"},
    ],
    "hsk5_002": [
        {"chinese": "哎呀，我把钥匙忘在家里了！", "pinyin": "Āiyā, wǒ bǎ yàoshi wàng zài jiā lǐ le!", "meaningVi": "Ôi trời, tôi quên chìa khóa ở nhà rồi!"},
    ],
    "hsk5_003": [
        {"chinese": "唉，这次考试我又没考好。", "pinyin": "Ài, zhè cì kǎoshì wǒ yòu méi kǎohǎo.", "meaningVi": "Haiz, lần thi này tôi lại không làm tốt."},
    ],
    "hsk5_004": [
        {"chinese": "我们要爱护公共设施。", "pinyin": "Wǒmen yào àihù gōnggòng shèshī.", "meaningVi": "Chúng ta phải giữ gìn các cơ sở vật chất công cộng."},
        {"chinese": "老师很爱护自己的学生。", "pinyin": "Lǎoshī hěn àihù zìjǐ de xuéshēng.", "meaningVi": "Giáo viên rất yêu thương học sinh của mình."},
    ],
    "hsk5_006": [
        {"chinese": "上车请系好安全带。", "pinyin": "Shàng chē qǐng jìhǎo ānquándài.", "meaningVi": "Lên xe xin thắt dây an toàn."},
        {"chinese": "安全带可以保护乘客的生命安全。", "pinyin": "Ānquándài kěyǐ bǎohù chéngkè de shēngmìng ānquán.", "meaningVi": "Dây an toàn có thể bảo vệ tính mạng của hành khách."},
    ],
    "hsk5_008": [
        {"chinese": "请帮我安装这个软件。", "pinyin": "Qǐng bāng wǒ ānzhuāng zhège ruǎnjiàn.", "meaningVi": "Xin giúp tôi cài đặt phần mềm này."},
        {"chinese": "工人正在安装新的空调。", "pinyin": "Gōngrén zhèngzài ānzhuāng xīn de kōngtiáo.", "meaningVi": "Công nhân đang lắp đặt máy điều hòa mới."},
    ],
    "hsk5_009": [
        {"chinese": "房间里太暗了，看不清楚。", "pinyin": "Fángjiān lǐ tài àn le, kàn bu qīngchu.", "meaningVi": "Trong phòng quá tối, không nhìn rõ."},
        {"chinese": "天渐渐暗了下来。", "pinyin": "Tiān jiànjiàn àn le xiàlái.", "meaningVi": "Trời dần dần tối lại."},
    ],
    "hsk5_010": [
        {"chinese": "为了准备考试，他连续熬夜了三天。", "pinyin": "Wèile zhǔnbèi kǎoshì, tā liánxù áoyèle sān tiān.", "meaningVi": "Để chuẩn bị thi, anh ấy đã thức đêm liên tục ba ngày."},
        {"chinese": "熬夜对身体不好。", "pinyin": "Áoyè duì shēntǐ bù hǎo.", "meaningVi": "Thức đêm không tốt cho sức khỏe."},
    ],
    "hsk5_014": [
        {"chinese": "我们傍晚的时候去散步。", "pinyin": "Wǒmen bàngwǎn de shíhou qù sànbù.", "meaningVi": "Chúng tôi đi dạo vào lúc chiều muộn."},
        {"chinese": "傍晚的天空非常美丽。", "pinyin": "Bàngwǎn de tiānkōng fēicháng měilì.", "meaningVi": "Bầu trời lúc chiều muộn rất đẹp."},
    ],
    "hsk5_016": [
        {"chinese": "这个价格包含了早餐。", "pinyin": "Zhège jiàgé bāohánle zǎocān.", "meaningVi": "Giá này đã bao gồm bữa sáng."},
        {"chinese": "他的话里包含着深意。", "pinyin": "Tā de huà lǐ bāohánzhe shēnyì.", "meaningVi": "Trong lời nói của anh ấy chứa đựng ý nghĩa sâu xa."},
    ],
    "hsk5_017": [
        {"chinese": "参加者包括老师和学生。", "pinyin": "Cānjiāzhě bāokuò lǎoshī hé xuéshēng.", "meaningVi": "Người tham gia bao gồm giáo viên và học sinh."},
        {"chinese": "这个计划包括三个阶段。", "pinyin": "Zhège jìhuà bāokuò sān gè jiēduàn.", "meaningVi": "Kế hoạch này bao gồm ba giai đoạn."},
    ],
    "hsk5_019": [
        {"chinese": "这件衣服很薄，冬天穿不够暖和。", "pinyin": "Zhè jiàn yīfu hěn báo, dōngtiān chuān bú gòu nuǎnhuo.", "meaningVi": "Chiếc áo này rất mỏng, mặc mùa đông không đủ ấm."},
        {"chinese": "这本书很薄，一天就能看完。", "pinyin": "Zhè běn shū hěn báo, yì tiān jiù néng kànwán.", "meaningVi": "Cuốn sách này rất mỏng, một ngày là đọc xong."},
    ],
    "hsk5_020": [
        {"chinese": "这幅画是我家的宝。", "pinyin": "Zhè fú huà shì wǒ jiā de bǎo.", "meaningVi": "Bức tranh này là báu vật của nhà tôi."},
        {"chinese": "孩子是父母心中的宝。", "pinyin": "Háizi shì fùmǔ xīnzhōng de bǎo.", "meaningVi": "Con cái là báu vật trong lòng cha mẹ."},
    ],
    "hsk5_023": [
        {"chinese": "妈妈叫她的女儿“宝贝”。", "pinyin": "Māma jiào tā de nǚ'ér “bǎobèi”.", "meaningVi": "Mẹ gọi con gái mình là 'bảo bối'."},
        {"chinese": "这件古董是他最珍贵的宝贝。", "pinyin": "Zhè jiàn gǔdǒng shì tā zuì zhēnguì de bǎobèi.", "meaningVi": "Món đồ cổ này là bảo bối quý giá nhất của anh ấy."},
    ],
    "hsk5_024": [
        {"chinese": "请保持安静。", "pinyin": "Qǐng bǎochí ānjìng.", "meaningVi": "Xin giữ yên lặng."},
        {"chinese": "他一直保持着良好的习惯。", "pinyin": "Tā yìzhí bǎochízhe liánghǎo de xíguàn.", "meaningVi": "Anh ấy luôn duy trì thói quen tốt."},
    ],
    "hsk5_025": [
        {"chinese": "记得保存你的文件。", "pinyin": "Jìde bǎocún nǐ de wénjiàn.", "meaningVi": "Nhớ lưu tệp của bạn."},
        {"chinese": "这些老照片保存得很好。", "pinyin": "Zhèxiē lǎo zhàopiàn bǎocún de hěn hǎo.", "meaningVi": "Những bức ảnh cũ này được bảo quản rất tốt."},
    ],
    "hsk5_026": [
        {"chinese": "时间是最宝贵的财富。", "pinyin": "Shíjiān shì zuì bǎoguì de cáifù.", "meaningVi": "Thời gian là tài sản quý giá nhất."},
        {"chinese": "他给了我们很多宝贵的建议。", "pinyin": "Tā gěile wǒmen hěn duō bǎoguì de jiànyì.", "meaningVi": "Anh ấy đã cho chúng tôi rất nhiều lời khuyên quý giá."},
    ],
    "hsk5_027": [
        {"chinese": "我们对这个方案保留意见。", "pinyin": "Wǒmen duì zhège fāng'àn bǎoliú yìjiàn.", "meaningVi": "Chúng tôi bảo lưu ý kiến về phương án này."},
        {"chinese": "这座老房子还保留着传统的样子。", "pinyin": "Zhè zuò lǎo fángzi hái bǎoliúzhe chuántǒng de yàngzi.", "meaningVi": "Ngôi nhà cũ này vẫn giữ được dáng vẻ truyền thống."},
    ],
    "hsk5_029": [
        {"chinese": "这瓶牛奶的保质期是一个月。", "pinyin": "Zhè píng niúnǎi de bǎozhìqī shì yí gè yuè.", "meaningVi": "Hạn sử dụng của chai sữa này là một tháng."},
        {"chinese": "买东西的时候要看保质期。", "pinyin": "Mǎi dōngxi de shíhou yào kàn bǎozhìqī.", "meaningVi": "Khi mua đồ phải xem hạn sử dụng."},
    ],
    "hsk5_030": [
        {"chinese": "新生今天到学校报到。", "pinyin": "Xīnshēng jīntiān dào xuéxiào bàodào.", "meaningVi": "Sinh viên mới hôm nay đến trường làm thủ tục nhập học."},
        {"chinese": "请大家明天早上八点在这里报到。", "pinyin": "Qǐng dàjiā míngtiān zǎoshang bā diǎn zài zhèlǐ bàodào.", "meaningVi": "Mời mọi người sáng mai 8 giờ đến đây điểm danh."},
    ],
    "hsk5_034": [
        {"chinese": "昨晚下了一场暴雨。", "pinyin": "Zuówǎn xiàle yì chǎng bàoyǔ.", "meaningVi": "Tối qua có một trận mưa lớn."},
        {"chinese": "暴雨过后，街道上积了很多水。", "pinyin": "Bàoyǔ guòhòu, jiēdào shàng jīle hěn duō shuǐ.", "meaningVi": "Sau trận mưa lớn, trên đường có rất nhiều nước đọng."},
    ],
    "hsk5_037": [
        {"chinese": "他躲在门背后。", "pinyin": "Tā duǒ zài mén bèihòu.", "meaningVi": "Anh ấy trốn sau cánh cửa."},
        {"chinese": "不要在背后说别人的坏话。", "pinyin": "Búyào zài bèihòu shuō biérén de huàihuà.", "meaningVi": "Đừng nói xấu người khác sau lưng."},
    ],
    "hsk5_038": [
        {"chinese": "这张照片的背景是长城。", "pinyin": "Zhè zhāng zhàopiàn de bèijǐng shì Chángchéng.", "meaningVi": "Bối cảnh của bức ảnh này là Vạn Lý Trường Thành."},
        {"chinese": "了解历史背景有助于理解这部小说。", "pinyin": "Liǎojiě lìshǐ bèijǐng yǒuzhùyú lǐjiě zhè bù xiǎoshuō.", "meaningVi": "Hiểu bối cảnh lịch sử giúp ích cho việc hiểu tiểu thuyết này."},
    ],
    "hsk5_039": [
        {"chinese": "天冷了，该换厚被子了。", "pinyin": "Tiān lěng le, gāi huàn hòu bèizi le.", "meaningVi": "Trời lạnh rồi, nên đổi chăn dày hơn."},
        {"chinese": "他把被子叠得整整齐齐。", "pinyin": "Tā bǎ bèizi dié de zhěngzhěngqíqí.", "meaningVi": "Anh ấy gấp chăn gọn gàng ngăn nắp."},
    ],
    "hsk5_041": [
        {"chinese": "这是本地的特色小吃。", "pinyin": "Zhè shì běndì de tèsè xiǎochī.", "meaningVi": "Đây là món ăn vặt đặc sản của địa phương."},
        {"chinese": "他不是本地人，是从外地来的。", "pinyin": "Tā bú shì běndì rén, shì cóng wàidì lái de.", "meaningVi": "Anh ấy không phải người bản địa, mà từ nơi khác đến."},
    ],
    "hsk5_042": [
        {"chinese": "他有一身好本领。", "pinyin": "Tā yǒu yìshēn hǎo běnlǐng.", "meaningVi": "Anh ấy có rất nhiều tài năng."},
        {"chinese": "游泳是他从小学会的本领。", "pinyin": "Yóuyǒng shì tā cóngxiǎo xuéhuì de běnlǐng.", "meaningVi": "Bơi lội là kỹ năng anh ấy học được từ nhỏ."},
    ],
    "hsk5_044": [
        {"chinese": "我们要看问题的本质。", "pinyin": "Wǒmen yào kàn wèntí de běnzhì.", "meaningVi": "Chúng ta phải nhìn vào bản chất của vấn đề."},
        {"chinese": "他本质上是一个善良的人。", "pinyin": "Tā běnzhì shàng shì yí gè shànliáng de rén.", "meaningVi": "Về bản chất, anh ấy là một người tốt bụng."},
    ],
    "hsk5_046": [
        {"chinese": "比赛的比分是三比二。", "pinyin": "Bǐsài de bǐfēn shì sān bǐ èr.", "meaningVi": "Tỷ số trận đấu là ba - hai."},
        {"chinese": "最后一分钟，比分被对方追平了。", "pinyin": "Zuìhòu yì fēnzhōng, bǐfēn bèi duìfāng zhuīpíng le.", "meaningVi": "Phút cuối cùng, tỷ số bị đối phương gỡ hòa."},
    ],
    "hsk5_047": [
        {"chinese": "男女比例大概是一比一。", "pinyin": "Nánnǚ bǐlì dàgài shì yī bǐ yī.", "meaningVi": "Tỷ lệ nam nữ khoảng một - một."},
        {"chinese": "这幅画的比例不太协调。", "pinyin": "Zhè fú huà de bǐlì bú tài xiétiáo.", "meaningVi": "Tỷ lệ của bức tranh này không được hài hòa lắm."},
    ],
    "hsk5_051": [
        {"chinese": "我们应该避免犯同样的错误。", "pinyin": "Wǒmen yīnggāi bìmiǎn fàn tóngyàng de cuòwù.", "meaningVi": "Chúng ta nên tránh mắc phải sai lầm tương tự."},
        {"chinese": "早点出发可以避免堵车。", "pinyin": "Zǎodiǎn chūfā kěyǐ bìmiǎn dǔchē.", "meaningVi": "Xuất phát sớm có thể tránh kẹt xe."},
    ],
    "hsk6_0001": [
        {"chinese": "船慢慢靠近了岸边。", "pinyin": "Chuán mànmàn kàojìnle àn biān.", "meaningVi": "Con thuyền từ từ tiến gần đến bờ."},
        {"chinese": "河的对岸有一座小村庄。", "pinyin": "Hé de duì'àn yǒu yí zuò xiǎo cūnzhuāng.", "meaningVi": "Bên kia bờ sông có một ngôi làng nhỏ."},
    ],
    "hsk6_0002": [
        {"chinese": "老师举了一个实际案例来说明。", "pinyin": "Lǎoshī jǔle yí gè shíjì ànlì lái shuōmíng.", "meaningVi": "Giáo viên đưa ra một ví dụ thực tế để minh họa."},
        {"chinese": "这个案例值得我们研究。", "pinyin": "Zhège ànlì zhídé wǒmen yánjiū.", "meaningVi": "Trường hợp này đáng để chúng ta nghiên cứu."},
    ],
    "hsk6_0003": [
        {"chinese": "工作累了，去做个按摩吧。", "pinyin": "Gōngzuò lèi le, qù zuò gè ànmó ba.", "meaningVi": "Làm việc mệt rồi, đi mát-xa đi."},
        {"chinese": "医生教她怎么给孩子按摩。", "pinyin": "Yīshēng jiāo tā zěnme gěi háizi ànmó.", "meaningVi": "Bác sĩ dạy cô ấy cách mát-xa cho trẻ."},
    ],
    "hsk6_0004": [
        {"chinese": "他的话暗示着一些不满。", "pinyin": "Tā de huà ànshìzhe yìxiē bùmǎn.", "meaningVi": "Lời nói của anh ấy ngầm ám chỉ một số bất mãn."},
        {"chinese": "老师用眼神暗示我别说话。", "pinyin": "Lǎoshī yòng yǎnshén ànshì wǒ bié shuōhuà.", "meaningVi": "Giáo viên dùng ánh mắt ra hiệu cho tôi đừng nói."},
    ],
    "hsk6_0005": [
        {"chinese": "这件首饰非常昂贵。", "pinyin": "Zhè jiàn shǒushì fēicháng ángguì.", "meaningVi": "Món trang sức này rất đắt tiền."},
        {"chinese": "治疗这种病需要昂贵的费用。", "pinyin": "Zhìliáo zhè zhǒng bìng xūyào ángguì de fèiyòng.", "meaningVi": "Điều trị căn bệnh này cần chi phí đắt đỏ."},
    ],
    "hsk6_0006": [
        {"chinese": "他白白浪费了三年时间。", "pinyin": "Tā báibái làngfèile sān nián shíjiān.", "meaningVi": "Anh ấy đã lãng phí ba năm thời gian một cách vô ích."},
        {"chinese": "别让这次机会白白错过。", "pinyin": "Bié ràng zhè cì jīhuì báibái cuòguò.", "meaningVi": "Đừng để cơ hội lần này trôi qua một cách uổng phí."},
    ],
    "hsk6_0007": [
        {"chinese": "她是一名典型的白领。", "pinyin": "Tā shì yì míng diǎnxíng de báilǐng.", "meaningVi": "Cô ấy là một nhân viên văn phòng điển hình."},
        {"chinese": "白领的工作压力通常比较大。", "pinyin": "Báilǐng de gōngzuò yālì tōngcháng bǐjiào dà.", "meaningVi": "Áp lực công việc của dân văn phòng thường khá lớn."},
    ],
    "hsk6_0008": [
        {"chinese": "她把花瓶摆在桌子上。", "pinyin": "Tā bǎ huāpíng bǎi zài zhuōzi shàng.", "meaningVi": "Cô ấy đặt bình hoa lên bàn."},
        {"chinese": "商店把新商品摆在最显眼的地方。", "pinyin": "Shāngdiàn bǎ xīn shāngpǐn bǎi zài zuì xiǎnyǎn de dìfang.", "meaningVi": "Cửa hàng bày sản phẩm mới ở nơi dễ thấy nhất."},
    ],
    "hsk6_0009": [
        {"chinese": "家具摆放得很整齐。", "pinyin": "Jiājù bǎifàng de hěn zhěngqí.", "meaningVi": "Đồ nội thất được sắp xếp rất gọn gàng."},
        {"chinese": "请把书按顺序摆放好。", "pinyin": "Qǐng bǎ shū àn shùnxù bǎifàng hǎo.", "meaningVi": "Xin hãy sắp xếp sách theo thứ tự."},
    ],
    "hsk6_0010": [
        {"chinese": "今年的增长率比去年高了两个百分点。", "pinyin": "Jīnnián de zēngzhǎnglǜ bǐ qùnián gāole liǎng gè bǎifēndiǎn.", "meaningVi": "Tỷ lệ tăng trưởng năm nay cao hơn năm ngoái hai điểm phần trăm."},
    ],
    "hsk6_0011": [
        {"chinese": "这家百货商店商品很齐全。", "pinyin": "Zhè jiā bǎihuò shāngdiàn shāngpǐn hěn qíquán.", "meaningVi": "Cửa hàng bách hóa này có hàng hóa rất đầy đủ."},
    ],
    "hsk6_0012": [
        {"chinese": "他终于摆脱了坏习惯。", "pinyin": "Tā zhōngyú bǎituōle huài xíguàn.", "meaningVi": "Cuối cùng anh ấy đã thoát khỏi thói quen xấu."},
        {"chinese": "她想摆脱现在的困境。", "pinyin": "Tā xiǎng bǎituō xiànzài de kùnjìng.", "meaningVi": "Cô ấy muốn thoát khỏi tình cảnh khó khăn hiện tại."},
    ],
    "hsk6_0013": [
        {"chinese": "我们队以一分之差败给了对手。", "pinyin": "Wǒmen duì yǐ yì fēn zhī chà bài gěi le duìshǒu.", "meaningVi": "Đội chúng tôi thua đối thủ chỉ vì một điểm."},
        {"chinese": "这场比赛他们败得很彻底。", "pinyin": "Zhè chǎng bǐsài tāmen bài de hěn chèdǐ.", "meaningVi": "Trận đấu này họ đã thua rất triệt để."},
    ],
    "hsk6_0014": [
        {"chinese": "明天我要去拜访一位老朋友。", "pinyin": "Míngtiān wǒ yào qù bàifǎng yí wèi lǎo péngyou.", "meaningVi": "Ngày mai tôi sẽ đi thăm một người bạn cũ."},
        {"chinese": "他专程拜访了这位著名的教授。", "pinyin": "Tā zhuānchéng bàifǎngle zhè wèi zhùmíng de jiàoshòu.", "meaningVi": "Anh ấy đã đặc biệt đến thăm vị giáo sư nổi tiếng này."},
    ],
    "hsk6_0015": [
        {"chinese": "春节的时候，我们去给爷爷奶奶拜年。", "pinyin": "Chūnjié de shíhou, wǒmen qù gěi yéye nǎinai bàinián.", "meaningVi": "Vào dịp Tết, chúng tôi đi chúc Tết ông bà."},
    ],
    "hsk6_0016": [
        {"chinese": "这本书出了第三版。", "pinyin": "Zhè běn shū chūle dì-sān bǎn.", "meaningVi": "Cuốn sách này đã ra bản in lần thứ ba."},
        {"chinese": "这篇报道登在报纸的头版。", "pinyin": "Zhè piān bàodào dēng zài bàozhǐ de tóubǎn.", "meaningVi": "Bài báo này được đăng ở trang nhất của tờ báo."},
    ],
    "hsk6_0017": [
        {"chinese": "这个软件已经更新到最新版本了。", "pinyin": "Zhège ruǎnjiàn yǐjīng gēngxīn dào zuìxīn bǎnběn le.", "meaningVi": "Phần mềm này đã được cập nhật lên phiên bản mới nhất."},
        {"chinese": "这个故事有好几个版本。", "pinyin": "Zhège gùshi yǒu hǎo jǐ gè bǎnběn.", "meaningVi": "Câu chuyện này có nhiều phiên bản."},
    ],
    "hsk6_0018": [
        {"chinese": "成功往往伴随着艰苦的努力。", "pinyin": "Chénggōng wǎngwǎng bànsuízhe jiānkǔ de nǔlì.", "meaningVi": "Thành công thường đi kèm với nỗ lực gian khổ."},
        {"chinese": "音乐伴随着他度过了艰难的岁月。", "pinyin": "Yīnyuè bànsuízhe tā dùguòle jiānnán de suìyuè.", "meaningVi": "Âm nhạc đã đồng hành cùng anh ấy vượt qua những năm tháng khó khăn."},
    ],
    "hsk6_0019": [
        {"chinese": "他在这部电影里扮演主角。", "pinyin": "Tā zài zhè bù diànyǐng lǐ bànyǎn zhǔjué.", "meaningVi": "Anh ấy đóng vai chính trong bộ phim này."},
        {"chinese": "父母在孩子的成长中扮演着重要的角色。", "pinyin": "Fùmǔ zài háizi de chéngzhǎng zhōng bànyǎnzhe zhòngyào de juésè.", "meaningVi": "Cha mẹ đóng vai trò quan trọng trong sự trưởng thành của con cái."},
    ],
    "hsk6_0020": [
        {"chinese": "他是我们学习的榜样。", "pinyin": "Tā shì wǒmen xuéxí de bǎngyàng.", "meaningVi": "Anh ấy là tấm gương để chúng tôi học tập."},
        {"chinese": "父母应该给孩子树立好的榜样。", "pinyin": "Fùmǔ yīnggāi gěi háizi shùlì hǎo de bǎngyàng.", "meaningVi": "Cha mẹ nên làm tấm gương tốt cho con cái."},
    ],
    "hsk6_0021": [
        {"chinese": "他从小就喜欢打棒球。", "pinyin": "Tā cóngxiǎo jiù xǐhuan dǎ bàngqiú.", "meaningVi": "Từ nhỏ anh ấy đã thích chơi bóng chày."},
    ],
    "hsk6_0022": [
        {"chinese": "请把贵重物品交给前台保管。", "pinyin": "Qǐng bǎ guìzhòng wùpǐn jiāo gěi qiántái bǎoguǎn.", "meaningVi": "Xin hãy giao đồ vật quý giá cho quầy lễ tân giữ."},
        {"chinese": "这份文件由他专门保管。", "pinyin": "Zhè fèn wénjiàn yóu tā zhuānmén bǎoguǎn.", "meaningVi": "Tài liệu này do anh ấy chuyên trách bảo quản."},
    ],
    "hsk6_0023": [
        {"chinese": "老年人应该多注意保健。", "pinyin": "Lǎonián rén yīnggāi duō zhùyì bǎojiàn.", "meaningVi": "Người cao tuổi nên chú ý chăm sóc sức khỏe nhiều hơn."},
        {"chinese": "适当运动是很好的保健方法。", "pinyin": "Shìdàng yùndòng shì hěn hǎo de bǎojiàn fāngfǎ.", "meaningVi": "Vận động vừa phải là phương pháp chăm sóc sức khỏe rất tốt."},
    ],
    "hsk6_0024": [
        {"chinese": "冬天要注意保暖，别感冒了。", "pinyin": "Dōngtiān yào zhùyì bǎonuǎn, bié gǎnmào le.", "meaningVi": "Mùa đông phải chú ý giữ ấm, đừng để bị cảm."},
    ],
    "hsk6_0025": [
        {"chinese": "这台电脑还在保修期内。", "pinyin": "Zhè tái diànnǎo hái zài bǎoxiū qī nèi.", "meaningVi": "Chiếc máy tính này vẫn còn trong thời gian bảo hành."},
    ],
    "hsk6_0026": [
        {"chinese": "政府努力保障老百姓的基本生活。", "pinyin": "Zhèngfǔ nǔlì bǎozhàng lǎobǎixìng de jīběn shēnghuó.", "meaningVi": "Chính phủ nỗ lực đảm bảo cuộc sống cơ bản của người dân."},
        {"chinese": "良好的睡眠是健康的保障。", "pinyin": "Liánghǎo de shuìmián shì jiànkāng de bǎozhàng.", "meaningVi": "Giấc ngủ tốt là sự đảm bảo cho sức khỏe."},
    ],
    # hsk6_0027 (爆, "chiên nhanh") intentionally omitted -- flagged needs_review,
    # see PILOT_NEEDS_REVIEW below. Do not guess an example for it.
    "hsk6_0028": [
        {"chinese": "火山突然爆发了。", "pinyin": "Huǒshān tūrán bàofā le.", "meaningVi": "Núi lửa đột nhiên phun trào."},
        {"chinese": "他心中压抑已久的情绪终于爆发了。", "pinyin": "Tā xīnzhōng yāyì yǐjiǔ de qíngxù zhōngyú bàofā le.", "meaningVi": "Cảm xúc bị kìm nén lâu ngày trong lòng anh ấy cuối cùng đã bùng phát."},
    ],
    "hsk6_0029": [
        {"chinese": "图书馆订阅了很多报刊。", "pinyin": "Túshūguǎn dìngyuèle hěn duō bàokān.", "meaningVi": "Thư viện đã đặt mua rất nhiều báo chí, tạp chí."},
    ],
    "hsk6_0030": [
        {"chinese": "电视上不应该出现太多暴力内容。", "pinyin": "Diànshì shàng bù yīnggāi chūxiàn tài duō bàolì nèiróng.", "meaningVi": "Trên truyền hình không nên xuất hiện quá nhiều nội dung bạo lực."},
        {"chinese": "他反对用暴力解决问题。", "pinyin": "Tā fǎnduì yòng bàolì jiějué wèntí.", "meaningVi": "Anh ấy phản đối dùng bạo lực để giải quyết vấn đề."},
    ],
    "hsk6_0031": [
        {"chinese": "这次调查暴露了很多问题。", "pinyin": "Zhè cì diàochá bàolùle hěn duō wèntí.", "meaningVi": "Cuộc điều tra lần này đã phơi bày rất nhiều vấn đề."},
        {"chinese": "他一紧张就暴露了自己的秘密。", "pinyin": "Tā yì jǐnzhāng jiù bàolùle zìjǐ de mìmì.", "meaningVi": "Anh ấy vừa căng thẳng là đã để lộ bí mật của mình."},
    ],
    "hsk6_0032": [
        {"chinese": "他大学毕业后进了一家报社工作。", "pinyin": "Tā dàxué bìyè hòu jìnle yì jiā bàoshè gōngzuò.", "meaningVi": "Sau khi tốt nghiệp đại học, anh ấy vào làm việc tại một tòa soạn báo."},
    ],
    "hsk6_0033": [
        {"chinese": "工厂里突然发生了爆炸。", "pinyin": "Gōngchǎng lǐ tūrán fāshēngle bàozhà.", "meaningVi": "Trong nhà máy đột nhiên xảy ra vụ nổ."},
        {"chinese": "气球吹得太大就会爆炸。", "pinyin": "Qìqiú chuī de tài dà jiù huì bàozhà.", "meaningVi": "Bóng bay thổi quá to sẽ nổ."},
    ],
}

# Records selected by select_pilot_ids() but deliberately withheld from
# EXAMPLES_CONTENT because a confident, safe example could not be
# authored -- see module docstring / P5.10.2 report for the reasoning.
PILOT_NEEDS_REVIEW: dict[str, str] = {
    "hsk6_0027": (
        "爆 (bào) is tagged in production as a bound cooking-technique "
        "verb (meaningVi: 'chiên nhanh' / quick-fry), which is an unusual, "
        "narrow, and rarely-standalone sense (爆 is far more commonly seen "
        "in compounds like 爆发/爆炸, which are separate production "
        "records at hsk6_0028/hsk6_0033). A natural standalone sentence risks "
        "either sounding unnatural or accidentally demonstrating the far more "
        "common 'burst/explode' sense instead. Flagged needs_review rather than "
        "guessed, per the explicit generation-safety rule."
    ),
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Report selection only, write nothing.")
    args = parser.parse_args()

    universe = load_universe()
    tiers = classify_risk_tiers(universe)
    selected_ids, alloc, eligible_counts = select_pilot_ids(universe, tiers)

    if len(selected_ids) != TARGET_PILOT_SIZE:
        fail(f"selection produced {len(selected_ids)} records, expected {TARGET_PILOT_SIZE}")

    level_counts = defaultdict(int)
    for rid in selected_ids:
        level_counts[universe[rid]["_level"]] += 1

    print("=== P5.10.2 pilot selection ===")
    print(f"eligible per level (tier1+2 only): {dict(eligible_counts)}")
    print(f"allocation: {dict(alloc)}")
    print(f"selected: {len(selected_ids)} records")
    print(f"level distribution of selected: {dict(level_counts)}")
    tier_dist = defaultdict(int)
    for rid in selected_ids:
        tier_dist[tiers[rid]] += 1
    print(f"risk tier distribution of selected: {dict(tier_dist)}")

    if args.dry_run:
        print("=== DRY RUN: no files written ===")
        return

    if OUTPUT_PATH.exists():
        fail(f"{OUTPUT_PATH} already exists -- this script refuses to overwrite an existing pilot artifact.")

    missing_content = [rid for rid in selected_ids if rid not in EXAMPLES_CONTENT and rid not in PILOT_NEEDS_REVIEW]
    if missing_content:
        fail(f"selected record(s) have no authored content and are not flagged needs_review: {missing_content}")

    # source production hashes, per level actually touched by this pilot
    source_hashes = {}
    for n in sorted(level_counts.keys()):
        path = REPO_ROOT / "data" / "hsk" / f"hsk{n}" / f"hsk{n}_vocabulary_production.json"
        source_hashes[f"hsk{n}"] = hashlib.sha256(load_json_text(path).encode("utf-8")).hexdigest()

    generated_at = datetime.now(timezone.utc).isoformat()

    records_out = []
    total_examples = 0
    for rid in selected_ids:
        r = universe[rid]
        level = r["_level"]
        if rid in PILOT_NEEDS_REVIEW:
            records_out.append({
                "sourceId": rid,
                "sourceWord": r["word"],
                "hskLevel": level,
                "riskTier": tiers[rid],
                "qaStatus": "needs_review",
                "reviewerStatus": "unreviewed",
                "needsReviewReason": PILOT_NEEDS_REVIEW[rid],
                "examples": [],
            })
            continue
        examples = EXAMPLES_CONTENT[rid]
        total_examples += len(examples)
        records_out.append({
            "sourceId": rid,
            "sourceWord": r["word"],
            "hskLevel": level,
            "riskTier": tiers[rid],
            "qaStatus": "pending",
            "reviewerStatus": "unreviewed",
            "examples": examples,
        })

    artifact = {
        "pilotVersion": PILOT_VERSION,
        "generationBatch": GENERATION_BATCH,
        "generatedAt": generated_at,
        "generationMethod": GENERATION_METHOD,
        "generatorScript": "tools/hsk/examples/generate_hsk_examples_p102.py",
        "selectionRuleSummary": (
            "Deterministic: exclude risk tier 3 (homograph, different reading) "
            "and tier 4 (same-level same-pinyin duplicate); allocate 100 slots "
            "across HSK1-6 proportional to each level's eligible (tier1+2) "
            "count via largest-remainder rounding; within each level take the "
            "lowest-risk-first, id-ascending-sorted eligible records up to that "
            "level's allocation."
        ),
        "sourceProductionHashes": source_hashes,
        "pilotSize": len(records_out),
        "recordsWithExamples": sum(1 for r in records_out if r["examples"]),
        "recordsNeedsReview": sum(1 for r in records_out if r["qaStatus"] == "needs_review"),
        "totalExamples": total_examples,
        "records": records_out,
    }

    output_text = json.dumps(artifact, indent=2, ensure_ascii=False) + "\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="") as f:
        f.write(output_text)

    print(f"Wrote {OUTPUT_PATH}")
    print(f"records={len(records_out)} total_examples={total_examples} needs_review={artifact['recordsNeedsReview']}")


if __name__ == "__main__":
    main()
